const list = [
    {
      id: 1,
      title: "Блины с беконом",
      author: "by Wonder House Books | 25 April 2018",
      price: 60,
      img: "http://manavi.md/wp-content/uploads/2022/06/vetchina_bliny_1__1_-removebg-preview-1-1-300x300.png",
      amount: 1,
      category: 'hot dishes',
    },
    {
      id: 2,
      title: "Ассорти мясных деликатесов",
      author: "by Maple Press  | 1 September 2020",
      price: 180,
      img: "http://manavi.md/wp-content/uploads/2022/06/testpizza-600x600.png",
      amount: 1,
      category: 'salads',
    },
    {
      id: 3,
      title: "Гриль салат из телятины",
      author: "by Om Books Editorial Team  | 25 November 2018",
      price: 125,
      img: "http://manavi.md/wp-content/uploads/2022/06/formagi-300x300.png",
      amount: 1,
      category: 'salads',
    },
    {
      id: 4,
      title: "Блины с бананом и шоколадом",
      author: "by Wonder House Books | 25 April 2018",
      price: 50,
      img: "http://manavi.md/wp-content/uploads/2022/06/6acb8c5c-72ea-4602-8e51-5390c5ab39e9-300x300.webp",
      amount: 1,
      category:  'desserts' ,
    },
   
    {
      id: 5,
      title: "Хачапури аджарские",
      author: "by Wonder House Books  | 1 January 2018",
      price: 100,
      img: "http://manavi.md/wp-content/uploads/2022/06/frame-1-300x300.png",
      amount: 1,
      category: 'snacks',
    },
    {
      id: 6,
      title: "Pizza Manavi",
      author: "by Om Books Editorial Team | 30 September 2020",
      price: 120,
      img: "http://manavi.md/wp-content/uploads/2022/06/qutro-300x300.png",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 7,
      title: "Суп с тефтелями",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 65,
      img: "http://manavi.md/wp-content/uploads/2022/06/tefteli-1-300x300.png",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 8,
      title: "Хинкали Manavi c вершками",
      author: "by Wonder House Books  | 6 December 2020",
      price: 80,
      img: "http://manavi.md/wp-content/uploads/2022/07/veshki11-300x300.webp",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 9,
      title: "Цыплята <табака>",
      author: "by Content Team at Target Publications",
      price: 150,
      img: "http://manavi.md/wp-content/uploads/2022/06/czyplenok-tabaka-1-300x300.png",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 10,
      title: "Чашушули",
      author: "by Maple Press | 1 September 2021",
      price: 100,
      img: "http://manavi.md/wp-content/uploads/2022/06/chashushuli-300x300.webp",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 11,
      title: "Икра баклажанная",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 65,
      img: "http://manavi.md/wp-content/uploads/2022/06/1653202620564__1_-removebg-preview-300x300.webp",
      amount: 1,
      category: 'firts dishes',
    },
    {
      id: 12,
      title: "Krusovice",
      author: "by Sudha Murty | 1 January 2015",
      price: 50,
      img: "http://manavi.md/wp-content/uploads/2022/06/pivo-rozliv-scaled-300x300.webp",
      amount: 1,
      category: 'breakfasts',
    },
  ];
  
  export default list;